### ISSUE TITLE
400 response when trying to add a contact or group

### ISSUE THREAD

**Issue by giladaya** [dreamfactorysoftware/angular-sdk#10]
- New instance on enterprise.dreamfactory.com
- Followed the configuration procedure from the readme file.
- Registered as a new user via the app

Now, when I try to add a contact or a group, the POST request is sent but the response is a 400 with the message: `No record(s) detected in request.`

**Comment by giladaya** [comment]
Ok, did some investigations.
The request sent by this webapp has this payload (for adding new group):
`{"name":"test"}`

It seems like the backend expects the payload to be wrapped in another array. When (using cUrl) I issue a similar request but with the following payload, the request is successful and a new record is created:
`{"resource":{"name":"test"}}`

**Comment by HarveyEV** [comment]
Any plan on fixing the package?

**Comment by df-jablan** [comment]
Any records that you POST must be wrapped in a `resource`. This is how the DreamFactory API works and is documented on the [wiki](http://wiki.dreamfactory.com/DreamFactory/Tutorials/Posting_records).

**Comment by HarveyEV** [comment]
I understand that, but the sample application package is broken. That was my point.

**Comment by df-jablan** [comment]
Oh, I'm sorry, I didn't see you mention the sample application in your original message. Which sample application is exhibiting this behaviour?

**Comment by todda48** [comment]
We're working on it. Package file will be rebuilt.

**Comment by todda48** [comment]
Fixed in release 1.0.4.
